site_name: Learning DSA in Python
theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: brown
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: EB Garamond
  features:
    - content.code.copy
    - toc.integrate 
    - navigation.top

  logo: assets/lego.svg
  favicon: assets/lego_favicon.png

nav:
  - Home: index.md
  - Chapter 1 - Python Primer: DS&A-PythonPrimer.md
  - Chapter 2 - Object Oriented Programming: DS&A-Object-Oriented-Programming.md
  - Chapter 3 - Algorithm Analysis: DS&A-Algorithm-Analysis.md
  - Chapter 4 - Recursion: DS&A-Recursion.md
  - Chapter 5 - Array Based Sequences: DS&A-Array-Based-Sequences.md
  - Chapter 6 - Stacks Queues and Deques: DS&A-Stacks-Queues-and-Deques.md
  - Chapter 7 - Linked Lists: DS&A-Linked-Lists.md
  - Chapter 8 - Trees: DS&A-Trees.md
  - Chapter 9 - Priority Queues: DS&A-PriorityQueues.md
  - Chapter 10 - Maps HashTables and Skip Lists: DS&A-Maps-HashTables-and-Skip-Lists.md
  - Chapter 11 - Search Trees: DS&A-Search-Trees.md
  - Chapter 12 - Sorting and Selection: DS&A-Sorting-and-Selection.md
  - Chapter 13 - Text Processing: DS&A-Text-Processing.md
  - Chapter 14 - Graphs: DS&A-Graphs.md
  - Chapter 15 - Memory Management and B-Trees: DS&A-Memory-Management-and-B-Trees.md

repo_url: https://github.com/kantarcise/learningdsainpython

plugins:
   - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition # tip box

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css